language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"

env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=pep8

install:
    - "pip install -r requirements.txt"

script:
    - tox -e $TOX_ENV
